service: lambda-demo
plugins:
  - serverless-localstack

custom:
  localstack:
    debug: true
    stages:
     - local
     - dev
    endpointFile: localstack_endpoints.json
    
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x


functions:
  hello:
    handler: handler.hello